// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juftgsdlkbjqakfpltxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZnRnc2Rsa2JqcWFrZnBsdHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDk4OTQsImV4cCI6MjA2NDE4NTg5NH0.vAM4o0wTVrbIHrmMry4jM9Zbvh2XhJG8COek1KvJ6Zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);